import type { MainHomeModel } from '../../entities/main/types'

const thumb = '/thumbnail-placeholder.svg'

export const mainHomeData: MainHomeModel = {
  brand: {
    alt: 'Grapes and Goats Alliance 로고',
    title: 'Grapes & Goats',
    subtitle: 'Alliance',
  },
  heroSlides: [
    { id: 's1', line: 'AI 가 학습 경로를 추천해 주는' },
    { id: 's2', line: 'AI 가 코드 리뷰를 도와주는' },
    { id: 's3', line: 'AI 가 질문에 답해 주는' },
  ],
  categories: [
    { id: 'cat-backend', label: '백엔드' },
    { id: 'cat-frontend', label: '프론트엔드' },
    { id: 'cat-ai', label: 'AI' },
    { id: 'cat-bigdata', label: '빅데이터' },
    { id: 'cat-cloud', label: '클라우드' },
  ],
  lectures: [
    // 백엔드 — 8개 (5개 초과 시 화살표)
    {
      id: 'be-1',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'Spring Boot 입문 썸네일',
      title: 'Spring Boot 입문',
    },
    {
      id: 'be-2',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'REST API 설계 썸네일',
      title: 'REST API 설계',
    },
    {
      id: 'be-3',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'JPA·Hibernate 썸네일',
      title: 'JPA·Hibernate',
    },
    {
      id: 'be-4',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'MSA 기초 썸네일',
      title: 'MSA 기초',
    },
    {
      id: 'be-5',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'Redis 캐싱 썸네일',
      title: 'Redis 캐싱',
    },
    {
      id: 'be-6',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'Kafka 입문 썸네일',
      title: 'Kafka 입문',
    },
    {
      id: 'be-7',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: '보안·OAuth2 썸네일',
      title: '보안·OAuth2',
    },
    {
      id: 'be-8',
      categoryId: 'cat-backend',
      thumbnailSrc: thumb,
      thumbnailAlt: '배포·Docker 썸네일',
      title: '배포·Docker',
    },
    // 프론트엔드 — 6개
    {
      id: 'fe-1',
      categoryId: 'cat-frontend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'React 기초 썸네일',
      title: 'React 기초',
    },
    {
      id: 'fe-2',
      categoryId: 'cat-frontend',
      thumbnailSrc: thumb,
      thumbnailAlt: 'TypeScript 썸네일',
      title: 'TypeScript',
    },
    {
      id: 'fe-3',
      categoryId: 'cat-frontend',
      thumbnailSrc: thumb,
      thumbnailAlt: '상태관리 썸네일',
      title: '상태관리',
    },
    {
      id: 'fe-4',
      categoryId: 'cat-frontend',
      thumbnailSrc: thumb,
      thumbnailAlt: '테스트 썸네일',
      title: '테스트',
    },
    {
      id: 'fe-5',
      categoryId: 'cat-frontend',
      thumbnailSrc: thumb,
      thumbnailAlt: '성능 최적화 썸네일',
      title: '성능 최적화',
    },
    {
      id: 'fe-6',
      categoryId: 'cat-frontend',
      thumbnailSrc: thumb,
      thumbnailAlt: '접근성 썸네일',
      title: '접근성',
    },
    // AI — 5개 (화살표 없음)
    {
      id: 'ai-1',
      categoryId: 'cat-ai',
      thumbnailSrc: thumb,
      thumbnailAlt: 'LLM 개론 썸네일',
      title: 'LLM 개론',
    },
    {
      id: 'ai-2',
      categoryId: 'cat-ai',
      thumbnailSrc: thumb,
      thumbnailAlt: '프롬프트 엔지니어링 썸네일',
      title: '프롬프트 엔지니어링',
    },
    {
      id: 'ai-3',
      categoryId: 'cat-ai',
      thumbnailSrc: thumb,
      thumbnailAlt: 'RAG 썸네일',
      title: 'RAG',
    },
    {
      id: 'ai-4',
      categoryId: 'cat-ai',
      thumbnailSrc: thumb,
      thumbnailAlt: '파인튜닝 썸네일',
      title: '파인튜닝',
    },
    {
      id: 'ai-5',
      categoryId: 'cat-ai',
      thumbnailSrc: thumb,
      thumbnailAlt: '에이전트 썸네일',
      title: '에이전트',
    },
    // 빅데이터 — 7개
    {
      id: 'bd-1',
      categoryId: 'cat-bigdata',
      thumbnailSrc: thumb,
      thumbnailAlt: 'Spark 입문 썸네일',
      title: 'Spark 입문',
    },
    {
      id: 'bd-2',
      categoryId: 'cat-bigdata',
      thumbnailSrc: thumb,
      thumbnailAlt: '데이터 파이프라인 썸네일',
      title: '데이터 파이프라인',
    },
    {
      id: 'bd-3',
      categoryId: 'cat-bigdata',
      thumbnailSrc: thumb,
      thumbnailAlt: 'SQL·NoSQL 썸네일',
      title: 'SQL·NoSQL',
    },
    {
      id: 'bd-4',
      categoryId: 'cat-bigdata',
      thumbnailSrc: thumb,
      thumbnailAlt: '실시간 스트리밍 썸네일',
      title: '실시간 스트리밍',
    },
    {
      id: 'bd-5',
      categoryId: 'cat-bigdata',
      thumbnailSrc: thumb,
      thumbnailAlt: '데이터 품질 썸네일',
      title: '데이터 품질',
    },
    {
      id: 'bd-6',
      categoryId: 'cat-bigdata',
      thumbnailSrc: thumb,
      thumbnailAlt: 'BI·시각화 썸네일',
      title: 'BI·시각화',
    },
    {
      id: 'bd-7',
      categoryId: 'cat-bigdata',
      thumbnailSrc: thumb,
      thumbnailAlt: '클라우드 웨어하우스 썸네일',
      title: '클라우드 웨어하우스',
    },
    // 클라우드 — 5개
    {
      id: 'cl-1',
      categoryId: 'cat-cloud',
      thumbnailSrc: thumb,
      thumbnailAlt: 'AWS 기초 썸네일',
      title: 'AWS 기초',
    },
    {
      id: 'cl-2',
      categoryId: 'cat-cloud',
      thumbnailSrc: thumb,
      thumbnailAlt: 'Kubernetes 썸네일',
      title: 'Kubernetes',
    },
    {
      id: 'cl-3',
      categoryId: 'cat-cloud',
      thumbnailSrc: thumb,
      thumbnailAlt: 'CI/CD 썸네일',
      title: 'CI/CD',
    },
    {
      id: 'cl-4',
      categoryId: 'cat-cloud',
      thumbnailSrc: thumb,
      thumbnailAlt: 'IaC 썸네일',
      title: 'IaC',
    },
    {
      id: 'cl-5',
      categoryId: 'cat-cloud',
      thumbnailSrc: thumb,
      thumbnailAlt: '관측성 썸네일',
      title: '관측성',
    },
  ],
}
